name: camalig_gym
description: Camalig Fitness Gym Mobile Application
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_svg: ^2.0.10
  mobile_scanner: ^5.2.3
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios: true
  android: false
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/login.jpg
    - assets/images/forgot-password.jpg
    - assets/images/signup-1.jpg
    - assets/images/signup-2.jpg
